#!/usr/bin/env bash
# Build FleetKit desktop launchers: double-click wakes the backing service,
# opens its page and posts a notification with a live count.
#
# Targets
#   zcode   ~/Desktop/zcode验证.app    wake com.local.zcode-captcha-relay, open
#                                      :8910, report the captcha ticket pool
#   panel   ~/Desktop/FleetKit面板.app wake com.local.fleet-ui, open :8796,
#                                      report the bridge count
#   all     both (default)
#
# Usage: make_desktop_apps.sh [zcode|panel|all] [--desktop DIR] [--name NAME]
#
# Each wake tries launchd kickstart first and falls back to running the
# deployed script directly, so a click works whether or not the agent is
# loaded. The generated apps are self-contained; rebuild after moving the
# fleet tree.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/../.." && pwd)"
KIT="$REPO/kit"
RUNTIME="$REPO/runtime"
DESKTOP="${HOME}/Desktop"
ARG_NAME=""
TARGETS_RAW="all"

while [ $# -gt 0 ]; do
  case "$1" in
    zcode|panel|all) TARGETS_RAW="$1"; shift ;;
    --desktop) DESKTOP="$2"; shift 2 ;;
    --name) ARG_NAME="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: $0 [zcode|panel|all] [--desktop DIR] [--name NAME]"; exit 0 ;;
    *) echo "unexpected argument: $1" >&2; exit 1 ;;
  esac
done

# The deployed (runtime) copy of a script wins over the kit checkout: it is
# what the running services actually use.
first_existing() {
  local cand
  for cand in "$@"; do
    if [ -f "$cand" ]; then echo "$cand"; return 0; fi
  done
  return 1
}

PY_BIN="$RUNTIME/.venv/bin/python"
[ -x "$PY_BIN" ] || PY_BIN="$(command -v python3)"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

draw_icon() { # draw_icon <png> <theme: shield|gauge>
  "$PY_BIN" - "$1" "$2" <<'PY'
import math
import sys
from PIL import Image, ImageDraw

OUT, THEME = sys.argv[1], sys.argv[2]
S = 3072

if THEME == "shield":
    top, bottom = (251, 146, 60), (234, 88, 12)     # amber -> orange (verify)
else:
    top, bottom = (16, 185, 129), (6, 148, 162)    # emerald -> teal (fleet)

grad = Image.new("RGBA", (S, S))
gp = grad.load()
for y in range(S):
    t = 0.35 + 0.65 * y / S
    row = tuple(int(top[i] + (bottom[i] - top[i]) * t) for i in range(3))
    for x in range(S):
        gp[x, y] = (row[0], row[1], row[2], 255)

radius = int(S * 0.235)
mask = Image.new("L", (S, S), 0)
ImageDraw.Draw(mask).rounded_rectangle([0, 0, S - 1, S - 1], radius=radius, fill=255)
img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
img.paste(grad, (0, 0), mask)

glow = Image.new("RGBA", (S, S), (0, 0, 0, 0))
ImageDraw.Draw(glow).rounded_rectangle(
    [0, 0, S - 1, S - 1], radius=radius, outline=(255, 255, 255, 40), width=int(S * 0.012))
img = Image.alpha_composite(img, glow)

d = ImageDraw.Draw(img)
white = (255, 255, 255, 255)

def qbez(p0, p1, p2, n=64):
    pts = []
    for i in range(n + 1):
        t = i / n
        mt = 1 - t
        pts.append((mt * mt * p0[0] + 2 * mt * t * p1[0] + t * t * p2[0],
                    mt * mt * p0[1] + 2 * mt * t * p1[1] + t * t * p2[1]))
    return pts

if THEME == "shield":
    lw = int(S * 0.030)
    for side in (0, 1):
        sx = 0.335 if side == 0 else 0.665
        ex = 0.415 if side == 0 else 0.585
        ctrl = (0.34 if side == 0 else 0.66, 0.60)
        pts = qbez((sx * S, 0.325 * S), (ctrl[0] * S, ctrl[1] * S), (ex * S, 0.700 * S))
        d.line(pts, fill=white, width=lw, joint="curve")
    d.line([(0.335 * S, 0.325 * S), (0.665 * S, 0.325 * S)], fill=white, width=lw)
    d.line([(0.425 * S, 0.495 * S), (0.487 * S, 0.565 * S), (0.605 * S, 0.420 * S)],
           fill=white, width=int(S * 0.036), joint="curve")
else:
    cx, cy, r = 0.5 * S, 0.56 * S, 0.26 * S
    a0, a1 = 150.0, 390.0
    arc = []
    for i in range(97):
        a = math.radians(a0 + (a1 - a0) * i / 96)
        arc.append((cx + r * math.cos(a), cy + r * math.sin(a)))
    d.line(arc, fill=white, width=int(S * 0.030), joint="curve")
    for frac in (0.0, 0.25, 0.5, 0.75, 1.0):
        a = math.radians(a0 + (a1 - a0) * frac)
        d.line([(cx + r * 0.82 * math.cos(a), cy + r * 0.82 * math.sin(a)),
                (cx + r * 0.97 * math.cos(a), cy + r * 0.97 * math.sin(a))],
               fill=white, width=int(S * 0.018))
    a = math.radians(a0 + (a1 - a0) * 0.62)
    d.line([(cx, cy), (cx + r * 0.72 * math.cos(a), cy + r * 0.72 * math.sin(a))],
           fill=white, width=int(S * 0.034))
    rr = S * 0.032
    d.ellipse([cx - rr, cy - rr, cx + rr, cy + rr], fill=white)

img = img.resize((1024, 1024), Image.LANCZOS)
img.save(OUT)
PY
}

write_launch() { # write_launch <out.sh> key=value ...
  local out="$1"; shift
  cat > "$out.tpl" <<'TPL'
#!/usr/bin/env bash
# Generated by make_desktop_apps.sh (@@TARGET@@) -- do not edit by hand.
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
PORT="${@@PORT_ENV@@:-@@PORT_DEFAULT@@}"
URL="http://127.0.0.1:${PORT}/"
LABEL="@@LABEL@@"
HEALTH_PATH="@@HEALTH@@"
START='@@START@@'
LOG="/tmp/@@LOGSTEM@@.log"

up() { curl -fsS -m 3 "http://127.0.0.1:${PORT}${HEALTH_PATH}" >/dev/null 2>&1; }

wake() {
  if launchctl print "gui/$(id -u)/$LABEL" >/dev/null 2>&1; then
    launchctl kickstart -k "gui/$(id -u)/$LABEL" >/dev/null 2>&1 || true
  fi
  local i
  for i in 1 2 3 4 5 6 7 8 9 10 11 12; do
    up && return 0
    sleep 0.5
  done
  return 1
}

start_direct() {
  nohup bash -c "$START" >>"$LOG" 2>&1 &
  local i
  for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16; do
    up && return 0
    sleep 0.5
  done
  return 1
}

notify() {
  osascript -e "display notification \"$2\" with title \"$1\"" >/dev/null 2>&1 || true
}

if up; then
  :
elif wake; then
  notify "@@NOTIFY_TITLE@@" "@@NOTE@@"
elif start_direct; then
  notify "@@NOTIFY_TITLE@@" "@@NOTE@@"
else
  notify "@@NOTIFY_TITLE@@启动失败" "@@FAIL_HINT@@"
  exit 1
fi

open "$URL"
@@STATUS_BLOCK@@
notify "@@NOTIFY_TITLE@@已打开" "@@OPEN_NOTE@@"
TPL
  local kv
  for kv in "$@"; do
    local key="${kv%%=*}" val="${kv#*=}"
    "$PY_BIN" - "$out.tpl" "$key" "$val" <<'PY'
import sys
tpl, key, val = sys.argv[1], sys.argv[2], sys.argv[3]
s = open(tpl, encoding="utf-8").read()
open(tpl, "w", encoding="utf-8").write(s.replace("@@%s@@" % key, val))
PY
  done
  mv "$out.tpl" "$out"
  chmod +x "$out"
}

build_app() { # build_app <app_name> <theme> <launch.sh>
  local name="$1" theme="$2" launch="$3"
  local app="$DESKTOP/${name}.app"
  local iconset="$WORK/icon.iconset" tmp_png="$WORK/icon_1024.png"
  mkdir -p "$iconset"
  draw_icon "$tmp_png" "$theme"
  local spec dbl
  for spec in 16 32 128 256 512; do
    sips -z "$spec" "$spec" "$tmp_png" --out "$iconset/icon_${spec}x${spec}.png" >/dev/null
    dbl=$((spec * 2))
    sips -z "$dbl" "$dbl" "$tmp_png" --out "$iconset/icon_${spec}x${spec}@2x.png" >/dev/null
  done
  iconutil -c icns "$iconset" -o "$WORK/app.icns"

  cat > "$WORK/launcher.applescript" <<'EOS'
on run
	set appPath to POSIX path of (path to me)
	do shell script "bash " & quoted form of (appPath & "Contents/Resources/launch.sh")
end run
EOS

  rm -rf "$app"
  osacompile -o "$app" "$WORK/launcher.applescript"
  mkdir -p "$app/Contents/Resources"
  cp "$launch" "$app/Contents/Resources/launch.sh"
  cp "$WORK"/status_*.py "$app/Contents/Resources/" 2>/dev/null || true
  cp "$WORK/app.icns" "$app/Contents/Resources/applet.icns"
  chmod +x "$app/Contents/Resources/launch.sh"
  # On Sequoia/Tahoe the osacompile applet template ships an Assets.car whose
  # default script icon outranks CFBundleIconFile, so the custom applet.icns
  # never shows. Drop the catalog and the icns wins.
  rm -f "$app/Contents/Resources/Assets.car"
  if /usr/libexec/PlistBuddy -c "Print :CFBundleIconFile" "$app/Contents/Info.plist" >/dev/null 2>&1; then
    /usr/libexec/PlistBuddy -c "Set :CFBundleIconFile applet" "$app/Contents/Info.plist"
  else
    /usr/libexec/PlistBuddy -c "Add :CFBundleIconFile string applet" "$app/Contents/Info.plist"
  fi
  codesign --force --sign - "$app" >/dev/null 2>&1 || true
  touch "$app"
  /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
    -f -R -trusted "$app" >/dev/null 2>&1 || true
  echo "built $app"
}

build_zcode() {
  local relay name launch
  relay="$(first_existing "$RUNTIME/bridges/zcode/captcha-relay.py" \
                           "$KIT/bridges/zcode/captcha-relay.py")" || {
    echo "captcha-relay.py not found under $RUNTIME or $KIT" >&2; exit 1; }
  name="${ARG_NAME:-zcode验证}"
  launch="$WORK/zcode-launch.sh"
  cat > "$WORK/status_tickets.py" <<'PY'
import json, sys
try:
    print(json.load(sys.stdin).get("tickets", 0))
except Exception:
    print(0)
PY
  write_launch "$launch" \
    TARGET=zcode \
    PORT_ENV=ZCODE_CAPTCHA_RELAY_PORT \
    PORT_DEFAULT=8910 \
    LABEL=com.local.zcode-captcha-relay \
    HEALTH=/healthz \
    START="/usr/bin/python3 \"$relay\" --port \"\$PORT\"" \
    LOGSTEM=zcode-captcha-relay \
    NOTIFY_TITLE="zcode 验证页" \
    NOTE="relay 服务已唤醒，正在打开换票页" \
    FAIL_HINT="8910 未监听：launchctl kickstart -k gui/\$(id -u)/com.local.zcode-captcha-relay" \
    STATUS_BLOCK='TICKETS="$(curl -fsS -m 3 "http://127.0.0.1:${PORT}/status" 2>/dev/null | /usr/bin/python3 "$HERE/status_tickets.py" 2>/dev/null || echo 0)"' \
    OPEN_NOTE="票池可用 \${TICKETS:-0} 张；无感补票由看门狗每 120 秒自动进行"
  build_app "$name" shield "$launch"
  echo "  wake: com.local.zcode-captcha-relay -> http://127.0.0.1:8910/ (ticket pool)"
}

build_panel() {
  local ui_sh name launch
  ui_sh="$(first_existing "$RUNTIME/tools/status_ui.sh" "$KIT/tools/status_ui.sh")" || {
    echo "status_ui.sh not found under $RUNTIME or $KIT" >&2; exit 1; }
  name="${ARG_NAME:-FleetKit面板}"
  launch="$WORK/panel-launch.sh"
  cat > "$WORK/status_bridges.py" <<'PY'
import json, sys
try:
    print(len(json.load(sys.stdin).get("bridges", [])))
except Exception:
    print(0)
PY
  write_launch "$launch" \
    TARGET=panel \
    PORT_ENV=FLEET_UI_PORT \
    PORT_DEFAULT=8796 \
    LABEL=com.local.fleet-ui \
    HEALTH=/api/status \
    START="bash \"$ui_sh\" start" \
    LOGSTEM=fleet-ui-desktop \
    NOTIFY_TITLE="FleetKit 面板" \
    NOTE="面板服务已唤醒，正在打开状态页" \
    FAIL_HINT="8796 未监听：launchctl kickstart -k gui/\$(id -u)/com.local.fleet-ui" \
    STATUS_BLOCK='BRIDGES="$(curl -fsS -m 5 "http://127.0.0.1:${PORT}/api/status" 2>/dev/null | /usr/bin/python3 "$HERE/status_bridges.py" 2>/dev/null || echo 0)"' \
    OPEN_NOTE="在册 \${BRIDGES:-0} 座桥；签到/重启等操作都在页面上"
  build_app "$name" gauge "$launch"
  echo "  wake: com.local.fleet-ui -> http://127.0.0.1:8796/ (bridge dashboard)"
}

case "$TARGETS_RAW" in
  zcode) build_zcode ;;
  panel) build_panel ;;
  all) build_zcode; build_panel ;;
esac
