#!/usr/bin/env bash
# Build the zcode captcha desktop launcher (~/Desktop/zcode验证.app).
#
# The applet does three things on double-click: wake the 127.0.0.1:8910
# captcha relay (launchd service, direct python fallback), open the mint
# page, and post a notification with the ticket pool count. The keeper
# refills the pool offscreen; this shortcut is the manual entry point for
# when a mint has to be done by hand.
#
# Usage: bash make_zcode_captcha_app.sh [--desktop DIR] [--name NAME]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/../.." && pwd)"
KIT="$REPO/kit"
RUNTIME="$REPO/runtime"
DESKTOP="${HOME}/Desktop"
APP_NAME="zcode验证"

while [ $# -gt 0 ]; do
  case "$1" in
    --desktop) DESKTOP="$2"; shift 2 ;;
    --name) APP_NAME="$2"; shift 2 ;;
    -h|--help) echo "Usage: $0 [--desktop DIR] [--name NAME]"; exit 0 ;;
    *) echo "unexpected argument: $1" >&2; exit 1 ;;
  esac
done

# The deployed relay (what the launchd service actually runs) wins over the
# kit checkout; the kit copy is the direct-run fallback when no service exists.
RELAY=""
for cand in "$RUNTIME/bridges/zcode/captcha-relay.py" "$KIT/bridges/zcode/captcha-relay.py"; do
  if [ -f "$cand" ]; then RELAY="$cand"; break; fi
done
if [ -z "$RELAY" ]; then
  echo "captcha-relay.py not found under $RUNTIME or $KIT" >&2
  exit 1
fi

PY_BIN="${RUNTIME}/.venv/bin/python"
[ -x "$PY_BIN" ] || PY_BIN="$(command -v python3)"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# --- icon ------------------------------------------------------------------
ICONSET="$WORK/App.iconset"
mkdir -p "$ICONSET"
"$PY_BIN" - "$WORK/icon_1024.png" <<'PY'
import sys
from PIL import Image, ImageDraw

OUT = sys.argv[1]
S = 3072
img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
d = ImageDraw.Draw(img)

top = (79, 70, 229)      # indigo
bottom = (14, 165, 233)  # sky

def gradient_pixel(x, y):
    t = (0.35 * x + 0.65 * y) / S
    return tuple(int(top[i] + (bottom[i] - top[i]) * t) for i in range(3))

grad = Image.new("RGBA", (S, S))
gp = grad.load()
for y in range(S):
    row = gradient_pixel(0, y)
    for x in range(S):
        gp[x, y] = (row[0], row[1], row[2], 255)

radius = int(S * 0.235)
mask = Image.new("L", (S, S), 0)
ImageDraw.Draw(mask).rounded_rectangle([0, 0, S - 1, S - 1], radius=radius, fill=255)
img.paste(grad, (0, 0), mask)

# subtle inner highlight along the top edge
glow = Image.new("RGBA", (S, S), (0, 0, 0, 0))
gd = ImageDraw.Draw(glow)
gd.rounded_rectangle([0, 0, S - 1, S - 1], radius=radius, outline=(255, 255, 255, 40), width=int(S * 0.012))
img = Image.alpha_composite(img, glow)

d = ImageDraw.Draw(img)
white = (255, 255, 255, 255)
lw = int(S * 0.030)

def qbez(p0, p1, p2, n=64):
    pts = []
    for i in range(n + 1):
        t = i / n
        mt = 1 - t
        pts.append((mt * mt * p0[0] + 2 * mt * t * p1[0] + t * t * p2[0],
                    mt * mt * p0[1] + 2 * mt * t * p1[1] + t * t * p2[1]))
    return pts

# shield outline: two side curves down to the bottom vertex
for side in (0, 1):
    sx = 0.335 if side == 0 else 0.665
    ex = 0.415 if side == 0 else 0.585
    ctrl = (0.34 if side == 0 else 0.66, 0.60)
    pts = qbez((sx * S, 0.325 * S), (ctrl[0] * S, ctrl[1] * S), (ex * S, 0.700 * S))
    d.line(pts, fill=white, width=lw, joint="curve")
d.line([(0.335 * S, 0.325 * S), (0.665 * S, 0.325 * S)], fill=white, width=lw)

# check mark inside the shield
d.line([(0.425 * S, 0.495 * S), (0.487 * S, 0.565 * S), (0.605 * S, 0.420 * S)],
       fill=white, width=int(S * 0.036), joint="curve")

img = img.resize((1024, 1024), Image.LANCZOS)
img.save(OUT)
PY

for spec in 16 32 128 256 512; do
  sips -z "$spec" "$spec" "$WORK/icon_1024.png" --out "$ICONSET/icon_${spec}x${spec}.png" >/dev/null
  dbl=$((spec * 2))
  sips -z "$dbl" "$dbl" "$WORK/icon_1024.png" --out "$ICONSET/icon_${spec}x${spec}@2x.png" >/dev/null
done
iconutil -c icns "$ICONSET" -o "$WORK/App.icns"

# --- launcher payload ------------------------------------------------------
mkdir -p "$WORK/Contents/Resources"
cat > "$WORK/launch.sh" <<EOS
#!/usr/bin/env bash
# Generated by make_zcode_captcha_app.sh -- do not edit by hand.
set -uo pipefail

PORT="\${ZCODE_CAPTCHA_RELAY_PORT:-8910}"
URL="http://127.0.0.1:\${PORT}/"
LABEL="com.local.zcode-captcha-relay"
RELAY="$RELAY"
LOG="/tmp/zcode-captcha-relay.log"

up() { curl -fsS -m 2 "http://127.0.0.1:\${PORT}/healthz" >/dev/null 2>&1; }

wake() {
  if launchctl print "gui/\$(id -u)/\$LABEL" >/dev/null 2>&1; then
    launchctl kickstart -k "gui/\$(id -u)/\$LABEL" >/dev/null 2>&1 || true
  fi
  local i
  for i in 1 2 3 4 5 6 7 8 9 10 11 12; do
    up && return 0
    sleep 0.5
  done
  return 1
}

start_direct() {
  [ -f "\$RELAY" ] || return 1
  nohup /usr/bin/python3 "\$RELAY" --port "\$PORT" >>"\$LOG" 2>&1 &
  local i
  for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16; do
    up && return 0
    sleep 0.5
  done
  return 1
}

notify() {
  osascript -e "display notification \"\$2\" with title \"\$1\"" >/dev/null 2>&1 || true
}

if up; then
  :
elif wake; then
  notify "zcode 验证页" "relay 服务已唤醒，正在打开换票页"
elif start_direct; then
  notify "zcode 验证页" "relay 直启成功，正在打开换票页"
else
  notify "zcode 验证页启动失败" "8910 未监听：launchctl kickstart -k gui/\$(id -u)/\$LABEL"
  exit 1
fi

open "\$URL"

TICKETS="\$(curl -fsS -m 3 "http://127.0.0.1:\${PORT}/status" 2>/dev/null | /usr/bin/python3 -c 'import json,sys; print(json.load(sys.stdin).get("tickets", 0))' 2>/dev/null || echo 0)"
notify "zcode 验证页已打开" "票池可用 \${TICKETS:-0} 张；无感补票由看门狗每 120 秒自动进行"
EOS
chmod +x "$WORK/launch.sh"

# --- applet ----------------------------------------------------------------
cat > "$WORK/launcher.applescript" <<'EOS'
on run
	set appPath to POSIX path of (path to me)
	do shell script "bash " & quoted form of (appPath & "Contents/Resources/launch.sh")
end run
EOS

APP="$DESKTOP/${APP_NAME}.app"
rm -rf "$APP"
osacompile -o "$APP" "$WORK/launcher.applescript"
mkdir -p "$APP/Contents/Resources"
cp "$WORK/launch.sh" "$APP/Contents/Resources/launch.sh"
cp "$WORK/App.icns" "$APP/Contents/Resources/applet.icns"
chmod +x "$APP/Contents/Resources/launch.sh"
if /usr/libexec/PlistBuddy -c "Print :CFBundleIconFile" "$APP/Contents/Info.plist" >/dev/null 2>&1; then
  /usr/libexec/PlistBuddy -c "Set :CFBundleIconFile applet" "$APP/Contents/Info.plist"
else
  /usr/libexec/PlistBuddy -c "Add :CFBundleIconFile string applet" "$APP/Contents/Info.plist"
fi
codesign --force --sign - "$APP" >/dev/null 2>&1 || true

touch "$APP"
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
  -f -R -trusted "$APP" >/dev/null 2>&1 || true

echo "built $APP"
echo "relay: $RELAY (port \$ZCODE_CAPTCHA_RELAY_PORT or 8910)"
